### ISSUE TITLE
We have an exception when running demo-app from this repo.

### ISSUE THREAD

**Issue by Djumabaevs** [VincentMasselis/RxBluetoothKotlin#10]
\RxBluetoothKotlin-maven-central-migration\RxBluetoothKotlin-maven-central-migration\demo-app\app\src\main\java\com\vincentmasselis\demoapp\DeviceActivity.kt: (50, 14): Unresolved reference. None of the following candidates is applicable because of receiver type mismatch: 
public fun Disposable.disposeOnState(exceptedState: ActivityState, activityToMonitor: Activity): Disposable defined in com.vincentmasselis.rxuikotlin
public fun Disposable.disposeOnState(exceptedState: FragmentState, fragmentToMonitor: Fragment): Disposable defined in com.vincentmasselis.rxuikotlin
public fun Disposable.disposeOnState(exceptedState: ViewHolderState, viewHolderToMonitor: LifecycleViewHolder): Disposable defined in com.vincentmasselis.rxuikotlin

**Comment by VincentMasselis** [comment]
I just push the commit https://github.com/VincentMasselis/RxBluetoothKotlin/commit/ddd36298e8810d726cb04198dd3a57efad5e3f86 to fix your issue.

Please pull the latest commit on master and try again :)
