### ISSUE TITLE
BLE Enable notifications and read characteristic notification (listen change) 

### ISSUE THREAD

**Issue by Raidensama** [VincentMasselis/RxBluetoothKotlin#16]
Hi

I'm trying to establish BLE communication with an esp32. I succeed to do it in java but I'm trying to do it in Kotlin now. I run the demo app but it seems the Notifications are not used in the example. However I found a file named "ListenChangeTest.kt" I think the solution is in this file but I don't understand it. Can you explain how to use notifications in your example please ?

**Comment by VincentMasselis** [comment]
In order to listen for notification, you need to enable them first by using the method `enableNotification`.
For instance:
```
gatt.enableNotification(gatt.source.findCharacteristic(MY_CHARACTERISTIC)!!)
            .flatMapPublisher { gatt.listenChanges(gatt.source.findCharacteristic(MY_CHARACTERISTIC)!!) }
```
