### ISSUE TITLE
Cannot access class 'io.reactivex.Flowable'. Check your module classpath for missing or conflicting dependencies

### ISSUE THREAD

**Issue by chengpocheng** [VincentMasselis/RxBluetoothKotlin#2]
When I call `bluetoothManager.rxScan(context)`, and it appears "Cannot access class 'io.reactivex.Flowable'. Check your module classpath for missing or conflicting dependencies".

**Comment by VincentMasselis** [comment]
You have to add `implementation 'io.reactivex.rxjava2:rxjava:2.2.8'` to your dependencies along with `implementation 'com.vincentmasselis.rxbluetoothkotlin:rxbluetoothkotlin-core:1.0.1'`, RxBluetoothotlin doesn't provides the RxJava dependency by his own, you have to do by yourself.

**Comment by VincentMasselis** [comment]
I'll update the README.md dependency section
