### ISSUE TITLE
Type mismatch: inferred type is Application but Boolean was expected

### ISSUE THREAD

**Issue by techker** [VincentMasselis/RxBluetoothKotlin#6]
I got an issue in  DeviceActivity of demoApp

.switchMapSingle { device.connectRxGatt(applicationContext as Application) }
Type mismatch: inferred type is Application but Boolean was expected

Also ScanActivty
 .rxScan(this, flushEvery = 1L to TimeUnit.SECONDS)
Type mismatch: inferred type is ScanActivity but Pair<List<ScanFilter>, ScanSettings>? was expected

**Comment by VincentMasselis** [comment]
Fixed, please pull master again
